import type { Dossier } from "@/lib/schemas";

const statusLabel = { match: "Correspond", no_match: "Ne correspond pas", unknown: "À vérifier" } as const;
const confidenceLabel = { low: "Faible", medium: "Moyenne", high: "Élevée" } as const;

export function DossierView({ dossier, showDraft = true }: { dossier: Dossier; showDraft?: boolean }) {
  const sourceNumber = new Map(dossier.sources.map((source, index) => [source.id, index + 1]));
  const claims = new Map(dossier.claims.map((claim) => [claim.id, claim]));
  const refs = (ids: string[]) => <span className="source-refs">{ids.map((id) => <a key={id} href={`#source-${id}`} aria-label={`Voir la source ${sourceNumber.get(id)}`}>[{sourceNumber.get(id)}]</a>)}</span>;

  return <article className="dossier">
    <div className="dossier-intro"><div><p className="section-index">{dossier.preparation === 'manual' ? 'Fiche préparée manuellement' : 'Fiche préparée avec l’IA · à vérifier'}</p><h2>{dossier.associationName}</h2><p>{dossier.summary}{refs(dossier.summarySourceIds)}</p></div><div className="confidence-box"><span>Confiance globale</span><strong>{confidenceLabel[dossier.confidence]}</strong><p>{dossier.confidenceReason}</p></div></div>
    <div className="dossier-columns">
      <section className="panel dossier-section"><h3>Identité et activité</h3><dl className="facts"><dt>Localisation</dt><dd>{dossier.identity.location || "Non vérifiée"}{refs(dossier.identity.sourceIds.location)}</dd><dt>Site</dt><dd>{dossier.identity.website ? <a href={dossier.identity.website} target="_blank" rel="noreferrer">{dossier.identity.website}</a> : "Non vérifié"}{refs(dossier.identity.sourceIds.website)}</dd><dt>Activité</dt><dd>{dossier.identity.activity || "Non vérifiée"}{refs(dossier.identity.sourceIds.activity)}</dd></dl></section>
      <section className="panel dossier-section"><h3>Points de contact trouvés</h3><ul className="dossier-list">{dossier.contacts.map((contact, index) => <li key={`${contact.type}-${index}`}><strong>{contact.label}</strong><span>{contact.type === "form" ? <a href={contact.value} target="_blank" rel="noreferrer">Ouvrir le formulaire</a> : contact.value}{refs(contact.sourceIds)}</span></li>)}</ul>{!dossier.contacts.some((contact) => contact.type === "email") && <p className="subtle-note">Aucune adresse e-mail vérifiée dans ce dossier.</p>}</section>
    </div>
    <section className="panel dossier-section"><h3>Faits sourcés</h3><ul className="verified-list">{dossier.claims.filter((claim) => claim.kind === "fact").map((claim) => <li key={claim.id}>{claim.text}{refs(claim.sourceIds)}{claim.evidence.length > 0 && <details><summary>Passage justificatif</summary>{claim.evidence.map((proof, index) => <blockquote key={index}>{proof.quote}{refs([proof.sourceId])}</blockquote>)}</details>}</li>)}</ul></section>
    {dossier.qualification && <div className="dossier-columns" aria-label="Qualification sur deux axes">{([
      ["digitalDebt", "Dette numérique"],
      ["absorption", "Capacité à accueillir une mission"],
    ] as const).map(([key, title]) => { const axis = dossier.qualification![key]; return <section className="panel dossier-section qualification-axis" key={key}><h3>{title}</h3><p>{axis.assessment}{refs([...new Set(axis.claimIds.flatMap((id) => claims.get(id)?.sourceIds || []))])}</p><h4>Ce qui reste inconnu</h4><ul className="bullet-list">{axis.unknowns.map((item) => <li key={item}>{item}</li>)}</ul></section>; })}</div>}
    <section className="panel dossier-section"><h3>Correspondance avec votre ciblage</h3><div className="match-list">{dossier.matches.map((match) => <div className="match-row" key={match.criterion}><div><strong>{match.criterion}</strong><p>{match.explanation}{refs([...new Set(match.claimIds.flatMap((id) => claims.get(id)?.sourceIds || []))])}</p></div><span className={`match-state ${match.status}`}>{statusLabel[match.status]}</span></div>)}</div></section>
    <div className="dossier-columns"><section className="panel dossier-section"><h3>Signaux et interprétations</h3><div className="signal-list">{dossier.signals.map((signal) => { const claim = claims.get(signal.claimId); return <div key={signal.claimId}><strong>Observation</strong><p>{claim?.text}{refs(claim?.sourceIds || [])}</p><strong>Hypothèse · confiance {confidenceLabel[signal.confidence].toLowerCase()}</strong><p>{signal.interpretation}</p></div>; })}</div></section><section className="panel dossier-section"><h3>Réserves</h3><ul className="bullet-list">{dossier.reservations.map((item) => <li key={item}>{item}</li>)}</ul></section></div>
    <section className="panel dossier-section"><h3>Approche proposée</h3><p className="approach-angle">{dossier.approach.angle}</p><p>{dossier.approach.rationale}{refs(dossier.approach.sourceIds)}</p><h4>Avant toute prise de contact</h4><ul className="bullet-list">{dossier.approach.toVerify.map((item) => <li key={item}>{item}</li>)}</ul></section>
    {showDraft && dossier.draft && <section className="panel dossier-section draft-section"><div className="draft-head"><h3>Brouillon de message</h3><span>Non envoyé · à adapter</span></div><p><strong>Objet :</strong> {dossier.draft.subject}</p><pre>{dossier.draft.body}</pre><p className="subtle-note">Ce texte est un point de départ. Relisez-le et ajoutez votre signature avant toute utilisation.</p></section>}
    <section className="panel dossier-section source-section"><h3>Sources et accès</h3><ol>{dossier.sources.map((source, index) => <li id={`source-${source.id}`} key={source.id}><span className="source-number">{index + 1}</span><div>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{source.label}</a> : <span>{source.label}</span>}<p>{source.accessStatus === "available" ? "Consultée" : source.accessStatus === "unavailable" ? "Accès impossible" : "Non consultée"} le {source.consultedAt ? new Date(source.consultedAt).toLocaleDateString("fr-FR") : "date inconnue"} · {source.origin === "public_page" ? "Site public" : "Entrée utilisateur"}</p></div></li>)}</ol></section>
  </article>;
}
